apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-source-service
spec:
  type: NodePort
  selector:
    app: data-source
  ports:
    - protocol: TCP
      port: {{ .Values.datasource.port }}
      targetPort: {{ .Values.datasource.port }}
      nodePort: 30002
