apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datamart
spec:
  type: NodePort
  selector:
    app: datamart
  ports:
    - protocol: TCP
      port: {{ .Values.datamart.port }}
      targetPort: {{ .Values.datamart.port }}
      nodePort: 30003
