apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-service
spec:
  type: NodePort
  selector:
    app: model
  ports:
    - protocol: TCP
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
      nodePort: 30001
